#Note to myself at a later time, having embedded was causing the appveyor builds to not work.
version: 1.0.{build}
before_build:
  - nuget restore
build:
  parallel: true
  project: AlsekLib.sln
  include_nuget_references: true
  verbosity: minimal
after_build:
  - cmd: if %APPVEYOR_REPO_TAG%==true (appveyor SetVariable -Name VERSION_NAME -Value %APPVEYOR_REPO_TAG_NAME%) else (appveyor SetVariable -Name VERSION_NAME -Value beta)
  - cmd: 7z a AlsekLib-%VERSION_NAME%.zip -r .build\*
  - cmd: appveyor PushArtifact AlsekLib-%VERSION_NAME%.zip  
on_success:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 success $env:WEBHOOK_URL
on_failure:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 failure $env:WEBHOOK_URL
