# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - master
    - '*'

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
- job: Main
  steps:
  # NuGet
  - task: NuGetToolInstaller@1
    displayName: Install nuget tool
  - task: NuGetCommand@2
    displayName: Restore nuget packages
    inputs:
        restoreSolution: '$(solution)'
  - task: VSBuild@1
    inputs:
        solution: '$(solution)'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
  - task: ArchiveFiles@2
    inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/.build/'
        includeRootFolder: true
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/drop.zip'
        replaceExistingArchive: true
  - task: PublishBuildArtifacts@1
    inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'Artifacts'
        publishLocation: 'Container'

- job: Release
  dependsOn: Main
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/release*'))
  steps:
  - script: echo this only runs for releases
  - task: GitHubRelease@1
    inputs:
      gitHubConnection: 'github.com_AylaMeo'
      repositoryName: 'AylaMeo/AlsekLib'
      action: 'create'
      target: '$(Build.SourceVersion)'
      title: 'v$(Build.BuildNumber)'
      tagSource: 'userSpecifiedTag'
      tag: 'beta'
      isDraft: true
      changeLogCompareToRelease: 'lastNonDraftRelease'
      changeLogType: 'commitBased'