- name: .NetFramework Action Template
  uses: auycro/netframework-action-template@v0.0.2

on:
  push:
    branches: 
     - master
     - '*'
  pull_request:
    branches: 
     - master
     - '*'

jobs:
  #build-dotnet:
  #  name: Build dotnet
  #  runs-on: windows-latest
  #  steps:
  #    - name: Checkout
  #      uses: actions/checkout@v2
  #    - name: Build the Docker image
  #      run: docker build . --file Dockerfile --tag auycro/dotnet
  #      #run: docker build . --file Dockerfile --tag auycro/dotnet:$(date +%s)
  #    - name: Run the Docker image
  #      run: docker run --rm auycro/dotnet --version

  build-msbuild:
    name: Build msbuild
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build --file Dockerfile.msbuild --tag auycro/msbuild .
        #run: docker build . --file Dockerfile --tag auycro/dotnet:$(date +%s)
      - name: Run the Docker image
        run: docker run --rm auycro/msbuild --version